name: SCIVEC app

on:
    push:
        branches-ignore:
            - "test-*"
        tags-ignore:
    workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    build:
        name: Build app
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [macos-latest, ubuntu-latest, windows-latest]
        steps:
            - name: Check out code
              uses: actions/checkout@v4

            - name: Install windows build helpers
              if: startsWith(matrix.os, 'windows')
              run: choco install mingw

            - name: Install Linux dependencies
              if: startsWith(matrix.os, 'ubuntu')
              run: sudo apt install libgl-dev libglu1-mesa-dev

            - name: Configure
              env:
                  CMAKE_BUILD_TYPE: Release
              run: cmake -G "Unix Makefiles" -B build

            - name: Build
              run: cmake --build build

            - name: Store
              uses: actions/upload-artifact@v4
              with:
                  name: binary-${{ matrix.os }}
                  path: build/scivec*

    publish:
        name: Publish
        needs: build
        runs-on: ubuntu-latest
        if: github.ref_type == 'tag'
        steps:
            - name: Set ARCHIVE
              run: echo ARCHIVE=scivec-${{ github.ref_name }}.tgz >> $GITHUB_ENV

            - name: Set TAG
              run: echo TAG=${GITHUB_REF:10} >> $GITHUB_ENV

            - uses: actions/download-artifact@4
              with:
                  path: scivec

            - run: chmod a+x scivec/*/scivec
            - run: ls -R scivec

            - name: Create archive
              run: tar czf ${ARCHIVE} -C scivec .

            - name: Publish
              uses: softprops/action-gh-release@v2
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  files: ${{ env.ARCHIVE }}
                  tag_name: ${{ github.ref }}
                  name: ${{ env.TAG }}
                  body: ""
                  draft: true
