name: SCIVEC app

on:
    push:
        branches-ignore:
            - "test-*"
    workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    build:
        name: Build app
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [macos-latest, ubuntu-latest, windows-latest]
        steps:
            - name: Check out code
              uses: actions/checkout@v4

            - name: Install windows build helpers
              if: startsWith(matrix.os, 'windows')
              run: choco install mingw

            - name: Install Linux dependencies
              if: startsWith(matrix.os, 'ubuntu')
              run: sudo apt install libgl-dev libglu1-mesa-dev

            - name: Configure
              env:
                  CMAKE_BUILD_TYPE: Release
              run: cmake -G "Unix Makefiles" -B build

            - name: Build
              run: cmake --build build

            - name: Store
              uses: actions/upload-artifact@v4
              with:
                  name: binary-${{ matrix.os }}
                  path: build/scivec*
